### ISSUE TITLE
不稳定的多人服务器连接

### ISSUE THREAD

**Issue by HotariTobu** [TartaricAcid/TouhouLittleMaid#308]
### 抱歉。 这可能是不自然的，因为Google Translate将其从日语翻译为简体中文。

我在多人游戏服务器上使用TouhouLittleMaid mod。
但是，此mod中的null pointer可能会使客户端连接不稳定。
发生错误时，附件是日志。

- “ Running.txt”是服务器启动且客户端播放器能够加入后发生的错误日志。
- “ BeforeStarting.txt”可能是服务器初始化时检测到的错误日志。

这个mod太好了，我希望它在多人游戏中玩起来很舒服。
谢谢你。

https://drive.google.com/drive/folders/1AFITGMpZDh8osKCFlIr226no_P3EYW7_?usp=sharing

**Comment by TartaricAcid** [comment]
The log you provided is too short, if possible, please provide the complete log content.
What version of `touhou little maid` are you using?

**Comment by HotariTobu** [comment]
I use "touhoulittlemaid-1.12.2-1.2.4-release.jar."

I updated the files in the above link.
UserName, PlayerName, and PlayerUUID were replaced.

**Comment by TartaricAcid** [comment]
I carefully analyzed the files you sent, and the results of the analysis are as follows:
1. `ScriptException` on the client: It is caused by the Java version being used too low. This problem can be avoided by replacing the Java version greater than 60. But it will not cause the game to crash, nor will it prevent players from connecting to the server.
2. `NullPointerException` on the server side: I carefully looked at the code in this place and can't found any problems. But I noticed that you are using the `mohist` server, there may be compatibility issues with it, but it does not seem to affect the running of the server.

**Comment by HotariTobu** [comment]
I see. Anyway, I update the Java runtime.
Thank you.
May I close this thread?

**Comment by TartaricAcid** [comment]
If there is no problem, you can close this issue

**Comment by HotariTobu** [comment]
I post an issue if there is any.
